version: '3.9'

networks:
  panda-net:
    name: panda-net
    driver: bridge

services:
  panda-api:
    container_name: panda-api
    restart: unless-stopped
    environment:
      - API_JWT_SECRET=${API_JWT_SECRET}
      - API_PORT=50000
      - BCRYPT_SALT_ROUNDS=12
      - NEO4J_HOST=panda-neo4j
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_SCHEMA="bolt://"
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - panda-api
    networks:
      - panda-net
    ports:
      - '127.0.0.1:50000:50000'
    platform: linux/amd64
