version: '3.9'

networks:
  panda-net:
    name: panda-net
    driver: bridge

services:

  panda-backend-api-gateway:
    container_name: panda-backend-api-gateway
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - panda-backend-api-gateway
    networks:
      - panda-net
    ports:
      - '127.0.0.1:50000:50000'
