version: "3.9"

networks:
  panda-net-test:
    name: panda-net-test
    driver: bridge

services:
  panda-api-test:
    container_name: panda-api-test
    restart: unless-stopped
    environment:
      - API_JWT_SECRET=${API_JWT_SECRET}
      - API_PORT=50100
      - BCRYPT_SALT_ROUNDS=12
      - NEO4J_HOST=panda-neo4j-test
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_SCHEMA=bolt://
      - API_INTEGRATION_B_OKBASE_GET_EMPLOYEES_URL=https://elieric.okbase.cz/okbase/service/rest/sestava/run
      - API_INTEGRATION_B_OKBASE_API_KEY=${API_INTEGRATION_B_OKBASE_API_KEY}
    build:
      context: ./
      dockerfile: Dockerfile.testenv
      labels:
        - panda-api-test
    networks:
      - panda-net-test
    ports:
      - "127.0.0.1:50100:50100"
    platform: linux/amd64
