version: "3.9"

networks:
  panda-net-dev:
    name: panda-net-dev
    driver: bridge
  panda-net-proxy:
    external: true

services:
  panda-api-dev:
    container_name: panda-api-dev
    restart: unless-stopped
    environment:
      - API_JWT_SECRET=${API_JWT_SECRET}
      - API_PORT=50200
      - BCRYPT_SALT_ROUNDS=12
      - NEO4J_HOST=panda-neo4j-dev
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_SCHEMA=bolt://
      - API_INTEGRATION_B_OKBASE_GET_EMPLOYEES_URL=https://elieric.okbase.cz/okbase/service/rest/sestava/run
      - API_INTEGRATION_B_OKBASE_API_KEY=${API_INTEGRATION_B_OKBASE_API_KEY}
      - API_INTEGRATION_B_WOS_STARTER_API_URL=https://api.clarivate.com/apis/wos-starter/v1
      - API_INTEGRATION_B_WOS_STARTER_API_KEY=${API_INTEGRATION_B_WOS_STARTER_API_KEY}
    build:
      context: ./
      dockerfile: Dockerfile.devenv
      labels:
        - panda-api-dev
    networks:
      - panda-net-dev
      - panda-net-proxy
    ports:
      - "127.0.0.1:50200:50200"
    platform: linux/amd64
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=panda-net-proxy"  # this has to be here if container has multiple networks!
      - "traefik.http.routers.panda-frontend-ui-main-app-dev.rule=Host(`panda-api.dev.eli-laser.eu`)"
      - "traefik.http.routers.panda-frontend-ui-main-app-dev.entrypoints=web,websecure"
      - "traefik.http.routers.panda-frontend-ui-main-app-dev.tls.certResolver=laser-http-staging"
