version: "3.9"

networks:
  panda-net-dev:
    name: panda-net-dev
    driver: bridge

services:
  panda-api-dev:
    container_name: panda-api-dev
    restart: unless-stopped
    environment:
      - API_JWT_SECRET=${API_JWT_SECRET}
      - API_PORT=50200
      - BCRYPT_SALT_ROUNDS=12
      - NEO4J_HOST=panda-neo4j-dev
      - NEO4J_PORT=7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_SCHEMA=bolt://
      - API_INTEGRATION_B_OKBASE_GET_EMPLOYEES_URL=https://elieric.okbase.cz/okbase/service/rest/sestava/run
      - API_INTEGRATION_B_OKBASE_API_KEY=${API_INTEGRATION_B_OKBASE_API_KEY}
      - API_INTEGRATION_B_WOS_STARTER_API_URL=https://api.clarivate.com/apis/wos-starter/v1
      - API_INTEGRATION_B_WOS_STARTER_API_KEY=${API_INTEGRATION_B_WOS_STARTER_API_KEY}
    build:
      context: ./
      dockerfile: Dockerfile.devenv
      labels:
        - panda-api-dev
    networks:
      - panda-net-dev
    ports:
      - "127.0.0.1:50200:50200"
    platform: linux/amd64
