version: '3.9'

networks:
  panda-net:
    name: panda-net
    driver: bridge

services:
  panda-security-neo4j:
    container_name: panda-security-neo4j
    image: neo4j:4.4.15@sha256:acf0ba298d912f3dc1649e482866368a816a3a38b21b59c68834c6da39493497
    # user: "1020:1020"
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/elipanda2022
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - "$HOME/panda-dev/neo4j-security/data:/data:rw"
      - "$HOME/panda-dev/neo4j-security/logs:/logs:rw"
      - "$HOME/panda-dev/neo4j-security/plugins:/plugins:rw"
      - "$HOME/panda-dev/neo4j-security/conf:/conf:rw"
      - "$HOME/panda-dev/neo4j-security/import:/import:rw"
    networks:
      - panda-net
    ports:
      - "7400:7474"
      - "7600:7687"
