// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Jiří Švácha",
            "email": "jiri.svacha@eli-beams.eu"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/catalogue/service/type": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create catalogue service type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogue"
                ],
                "summary": "Create catalogue service type",
                "parameters": [
                    {
                        "description": "Catalogue service type",
                        "name": "catalogueServiceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CatalogueServiceType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CatalogueServiceType"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/catalogue/service/type/{uid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get catalogue service type by uid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogue"
                ],
                "summary": "Get catalogue service type by uid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CatalogueServiceType"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update catalogue service type",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogue"
                ],
                "summary": "Update catalogue service type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Catalogue service type",
                        "name": "catalogueServiceType",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CatalogueServiceType"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CatalogueServiceType"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete catalogue service type",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogue"
                ],
                "summary": "Delete catalogue service type",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/catalogue/service/types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get catalogue service types",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogue"
                ],
                "summary": "Get catalogue service types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CatalogueServiceType"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/general/{uid}/graph": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get graph by uid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Get graph by uid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.GraphResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/getuserbyazureidtoken": {
            "get": {
                "description": "Get user by azure id token",
                "tags": [
                    "Security"
                ],
                "summary": "Get user by azure id token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tenant ID",
                        "name": "tenantId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Azure ID Token",
                        "name": "azureIdToken",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserAuthInfo"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            }
        },
        "/v1/order": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update an order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update an order",
                "parameters": [
                    {
                        "description": "Order object that needs to be updated",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderDetail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrderDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Insert a new order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Insert a new order",
                "parameters": [
                    {
                        "description": "Order object that needs to be inserted",
                        "name": "order",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.OrderDetail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrderDetail"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/order/{uid}": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete an order by order UID",
                "tags": [
                    "Orders"
                ],
                "summary": "Delete an order",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/order/{uid}/orderlines/delivery": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update multiple order line delivery",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update multiple order line delivery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Items UIDs",
                        "name": "itemsUids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.OrderLine"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/order/{uid}/serviceline/{serviceItemUid}/delivery": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update service line delivery status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update service line delivery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Service Item UID",
                        "name": "serviceItemUid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service Line Delivery object",
                        "name": "serviceLineDelivery",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ServiceLineDelivery"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ServiceLine"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/order/{uid}/servicelines/delivery": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update multiple service line delivery status to delivered",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Update multiple service line delivery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order UID",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Service Item UIDs",
                        "name": "serviceItemUids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ServiceLine"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/orders/eun-for-print": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get items for EUN print",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Orders"
                ],
                "summary": "Get items for EUN print",
                "parameters": [
                    {
                        "type": "string",
                        "description": "EUNs",
                        "name": "euns",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ItemForEunPrint"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/physical-item/move": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Move physical item from one system to another",
                "tags": [
                    "Systems"
                ],
                "summary": "Move physical item",
                "parameters": [
                    {
                        "description": "Move physical item request model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PhysicalItemMovement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return destination system UID"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/physical-item/replace": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Replace physical items between two systems",
                "tags": [
                    "Systems"
                ],
                "summary": "Replace physical item",
                "parameters": [
                    {
                        "description": "Move physical item request model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PhysicalItemMovement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return destination system UID"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/publication": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create publication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Create publication",
                "parameters": [
                    {
                        "description": "Publication",
                        "name": "publication",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Publication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Publication"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/publication/wos/{doi}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get WOS data by DOI",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Get WOS data by DOI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "doi",
                        "name": "doi",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.WosAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/publication/{uid}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get publication by uid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Get publication by uid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Publication"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update publication",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Update publication",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Publication",
                        "name": "publication",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Publication"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Publication"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Delete publication by uid",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Delete publication by uid",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid",
                        "name": "uid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/publications": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get publications",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Get publications",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search",
                        "name": "search",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "pagination",
                        "name": "pagination",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Publication"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/publications/export": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "CSV header: Media Type,Code,Experimental System,User Call,User Experiment,DOI,Web Link,Open Access Type,Title,Authors,Authors Count,ELI Authors,ELI Authors Count,Journal Title,Volume,Issue,Pages,Pages Count,Cite As,Impact Factor,Quartile Basis,Quartile,Year Of Publication,Date Of Publication,Abstract,Keywords,OECD Ford,Grant,WOS Number,ISSN,E-ISSN,EID Scopus,Publishing Country,Language,Note,UID",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "Publications"
                ],
                "summary": "Get publications as CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "CSV file"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/v1/system": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new system with the given details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Systems"
                ],
                "summary": "Create new system",
                "parameters": [
                    {
                        "description": "System details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.System"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the UID of the created system",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing required fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/system/jira-import": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new system using data from a Jira import request",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Systems"
                ],
                "summary": "Create new system from Jira import request",
                "parameters": [
                    {
                        "description": "Jira system import data",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.JiraSystemImportRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns the UID of the created system",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad request - invalid input or system code already exists",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/system/system-code": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create new system with new unique system code based on system type and zone",
                "tags": [
                    "Systems"
                ],
                "summary": "Create new system with code",
                "parameters": [
                    {
                        "description": "System code request model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SystemCodeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.System"
                        }
                    },
                    "400": {
                        "description": "Bad request - missing required fields"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/locations-flat": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all locations flat list",
                "tags": [
                    "Systems"
                ],
                "summary": "Get all locations flat list",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Codebook"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/move": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Move systems to another parent system",
                "tags": [
                    "Systems"
                ],
                "summary": "Move systems",
                "parameters": [
                    {
                        "description": "Move systems request model",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SystemsMovement"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Return destination system UID"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/recalculate-spare-parts": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Recalculate spare parts for all systems",
                "tags": [
                    "Systems"
                ],
                "summary": "Recalculate spare parts",
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/reload": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get systems tree by UIDs",
                "tags": [
                    "Systems"
                ],
                "summary": "Get systems tree by UIDs",
                "parameters": [
                    {
                        "description": "Array of system tree UIDs",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.SystemTreeUid"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.System"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/sync-locations-by-eun": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sync system locations by EUNs",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Systems"
                ],
                "summary": "Sync system locations by EUNs",
                "parameters": [
                    {
                        "description": "EUN with location UID",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.EunLocation"
                            }
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No content"
                    },
                    "400": {
                        "description": "Bad request"
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/system-types": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all system types",
                "tags": [
                    "Systems"
                ],
                "summary": "Get all system types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Codebook"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/systems/zones": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get all zones",
                "tags": [
                    "Systems"
                ],
                "summary": "Get all zones",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Codebook"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error"
                    }
                }
            }
        },
        "/v1/uuid/v4": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get UUID v4 string",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "General"
                ],
                "summary": "Get UUID V4",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.AuthorsDepartment": {
            "type": "object",
            "properties": {
                "authorsCount": {
                    "description": "authorsCount is the authors count of the publication",
                    "type": "integer"
                },
                "department": {
                    "description": "department is the department of the publication",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Codebook"
                        }
                    ]
                }
            }
        },
        "models.CatalogueCategoryProperty": {
            "type": "object",
            "properties": {
                "defaultValue": {
                    "type": "string"
                },
                "listOfValues": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/models.CatalogueCategoryPropertyType"
                },
                "uid": {
                    "type": "string"
                },
                "unit": {
                    "$ref": "#/definitions/models.Codebook"
                }
            }
        },
        "models.CatalogueCategoryPropertyType": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.CatalogueItem": {
            "type": "object",
            "properties": {
                "catalogueNumber": {
                    "type": "string"
                },
                "category": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "categoryUID": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/panda_apigateway_services_catalogue-service_models.CatalogueItemDetail"
                    }
                },
                "lastUpdateTime": {
                    "type": "string"
                },
                "manufacturerNumber": {
                    "type": "string"
                },
                "manufacturerUrl": {
                    "type": "string"
                },
                "miniImageUrl": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "supplier": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.CatalogueServiceType": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "properties": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.Codebook": {
            "type": "object",
            "properties": {
                "additionalData": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.EunLocation": {
            "type": "object",
            "properties": {
                "eun": {
                    "type": "string"
                },
                "location_uid": {
                    "type": "string"
                }
            }
        },
        "models.GraphLink": {
            "type": "object",
            "properties": {
                "relationship": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "models.GraphNode": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "properties": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.GraphResponse": {
            "type": "object",
            "properties": {
                "links": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GraphLink"
                    }
                },
                "nodes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.GraphNode"
                    }
                }
            }
        },
        "models.ItemForEunPrint": {
            "type": "object",
            "properties": {
                "catalogueNumber": {
                    "type": "string"
                },
                "eun": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "manufacturer": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "integer"
                },
                "serialNumber": {
                    "type": "string"
                }
            }
        },
        "models.JiraSystemImportRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "linkName": {
                    "type": "string"
                },
                "linkUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentSystemUid": {
                    "type": "string"
                },
                "systemTypeUid": {
                    "type": "string"
                },
                "zoneUid": {
                    "type": "string"
                }
            }
        },
        "models.OrderDetail": {
            "type": "object",
            "properties": {
                "contractNumber": {
                    "type": "string"
                },
                "lastUpdateTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "orderDate": {
                    "type": "string"
                },
                "orderLines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.OrderLine"
                    }
                },
                "orderNumber": {
                    "type": "string"
                },
                "orderStatus": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "procurementResponsible": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "requestNumber": {
                    "type": "string"
                },
                "requestor": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "serviceLines": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ServiceLine"
                    }
                },
                "supplier": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.OrderLine": {
            "type": "object",
            "properties": {
                "catalogueNumber": {
                    "type": "string"
                },
                "catalogueUid": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "deliveredTime": {
                    "type": "string"
                },
                "eun": {
                    "type": "string"
                },
                "isDelivered": {
                    "type": "boolean"
                },
                "itemUsage": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "lastUpdateTime": {
                    "type": "string"
                },
                "location": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "serialNumber": {
                    "type": "string"
                },
                "system": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.PhysicalItem": {
            "type": "object",
            "properties": {
                "catalogueItem": {
                    "$ref": "#/definitions/models.CatalogueItem"
                },
                "currency": {
                    "type": "string"
                },
                "eun": {
                    "type": "string"
                },
                "itemUsage": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "orderNumber": {
                    "type": "string"
                },
                "orderUid": {
                    "type": "string"
                },
                "price": {},
                "serialNumber": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.PhysicalItemMovement": {
            "type": "object",
            "properties": {
                "condition": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "deleteSourceSystem": {
                    "type": "boolean"
                },
                "destinationSystemUid": {
                    "type": "string"
                },
                "itemUsage": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "location": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "parentSystemUid": {
                    "type": "string"
                },
                "sourceSystemUid": {
                    "type": "string"
                },
                "systemName": {
                    "type": "string"
                }
            }
        },
        "models.Publication": {
            "type": "object",
            "properties": {
                "abstract": {
                    "description": "abstract is the abstract of the publication",
                    "type": "string"
                },
                "allAuthors": {
                    "description": "allAuthors is the all authors of the publication",
                    "type": "string"
                },
                "allAuthorsCount": {
                    "description": "allAuthorsCount is the all authors count of the publication",
                    "type": "integer"
                },
                "authorsDepartments": {
                    "description": "authorsDepartments is the authors departments of the publication",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.AuthorsDepartment"
                    }
                },
                "authorsDepartmentsArray": {
                    "description": "authorsDepartmentsArray is the authors departments array of the publication",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "citeAs": {
                    "description": "citeAs is the citation of the publication",
                    "type": "string"
                },
                "code": {
                    "description": "code is the internal code of the publication",
                    "type": "string"
                },
                "dateOfPublication": {
                    "description": "dateOfPublication is the date of publication of the publication",
                    "type": "string"
                },
                "doi": {
                    "description": "doi is the unique identifier of the publication",
                    "type": "string"
                },
                "eidScopus": {
                    "description": "eidScopus is the eid scopus of the publication",
                    "type": "string"
                },
                "eissn": {
                    "description": "eissn is the eissn of the publication",
                    "type": "string"
                },
                "eliAuthors": {
                    "description": "eliAuthors is the eli authors of the publication",
                    "type": "string"
                },
                "eliAuthorsCount": {
                    "description": "eliAuthorsCount is the eli authors count of the publication",
                    "type": "integer"
                },
                "experimentalSystem": {
                    "description": "experimentalSystem is the experimental system of the publication",
                    "type": "string"
                },
                "grant": {
                    "description": "grant is the grant of the publication",
                    "type": "string"
                },
                "impactFactor": {
                    "description": "impactFactor is the impact factor of the publication",
                    "type": "number"
                },
                "issn": {
                    "description": "issn is the issn of the publication",
                    "type": "string"
                },
                "issue": {
                    "description": "issue is the issue of the publication",
                    "type": "integer"
                },
                "keywords": {
                    "description": "keywords is the keywords of the publication",
                    "type": "string"
                },
                "language": {
                    "description": "language is the language of the publication",
                    "type": "string"
                },
                "longJournalTitle": {
                    "description": "longJournalTitle is the long journal title of the publication",
                    "type": "string"
                },
                "mediaType": {
                    "description": "mediaType is the media type of the publication",
                    "type": "string"
                },
                "note": {
                    "description": "note is the note of the publication",
                    "type": "string"
                },
                "oecdFord": {
                    "description": "oecdFord is the oecd ford of the publication",
                    "type": "string"
                },
                "openAccessType": {
                    "description": "openAccessType is the open access type of the publication",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Codebook"
                        }
                    ]
                },
                "pages": {
                    "description": "pages is the pages of the publication",
                    "type": "string"
                },
                "pagesCount": {
                    "description": "pagesCount is the pages count of the publication",
                    "type": "integer"
                },
                "pdfFileName": {
                    "description": "pdfFileName is the name of the pdf file of the publication",
                    "type": "string"
                },
                "pdfFileUrl": {
                    "description": "pdfFileUrl is the url of the pdf file of the publication",
                    "type": "string"
                },
                "publishingCountry": {
                    "description": "publishingCountry is the publishing country of the publication",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Codebook"
                        }
                    ]
                },
                "quartil": {
                    "description": "quartil is the quartil of the publication",
                    "type": "string"
                },
                "quartilBasis": {
                    "description": "quartilBasis is the quartil basis of the publication",
                    "type": "string"
                },
                "shortJournalTitle": {
                    "description": "shortJournalTitle is the short journal title of the publication",
                    "type": "string"
                },
                "title": {
                    "description": "title is the title of the publication",
                    "type": "string"
                },
                "uid": {
                    "description": "uid is the unique identifier of the publication",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "updatedAt is the time when the publication was last updated",
                    "type": "string"
                },
                "userCall": {
                    "description": "userCall is the user call of the publication",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Codebook"
                        }
                    ]
                },
                "userExperiment": {
                    "description": "userExperiment is the user experiment of the publication",
                    "type": "string"
                },
                "volume": {
                    "description": "volume is the volume of the publication",
                    "type": "integer"
                },
                "webLink": {
                    "description": "webLink is the web link of the publication",
                    "type": "string"
                },
                "wosNumber": {
                    "description": "wosNumber is the wos number of the publication",
                    "type": "string"
                },
                "yearOfPublication": {
                    "description": "yearOfPublication is the year of publication of the publication",
                    "type": "string"
                }
            }
        },
        "models.ServiceLine": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "deliveredTime": {
                    "type": "string"
                },
                "details": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/panda_apigateway_services_catalogue-service_models.CatalogueItemDetail"
                    }
                },
                "eun": {
                    "type": "string"
                },
                "isDelivered": {
                    "type": "boolean"
                },
                "item": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "lastUpdateTime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "serialNumber": {
                    "type": "string"
                },
                "serviceType": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.ServiceLineDelivery": {
            "type": "object",
            "properties": {
                "isDelivered": {
                    "type": "boolean"
                }
            }
        },
        "models.System": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "hasSubsystems": {
                    "type": "boolean"
                },
                "history": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SystemHistory"
                    }
                },
                "importance": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "location": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "miniImageUrl": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "parentPath": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SystemSimpleResponse"
                    }
                },
                "parentUid": {
                    "type": "string"
                },
                "physicalItem": {
                    "$ref": "#/definitions/models.PhysicalItem"
                },
                "responsible": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "sparesIn": {
                    "type": "integer"
                },
                "sparesOut": {
                    "type": "integer"
                },
                "statistics": {
                    "$ref": "#/definitions/models.SystemStatistics"
                },
                "subSystems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.System"
                    }
                },
                "systemAlias": {
                    "type": "string"
                },
                "systemCode": {
                    "type": "string"
                },
                "systemLevel": {
                    "type": "string"
                },
                "systemType": {
                    "$ref": "#/definitions/models.Codebook"
                },
                "uid": {
                    "type": "string"
                },
                "zone": {
                    "$ref": "#/definitions/models.Codebook"
                }
            }
        },
        "models.SystemCodeRequest": {
            "type": "object",
            "properties": {
                "parentUid": {
                    "type": "string"
                },
                "systemTypeUid": {
                    "type": "string"
                },
                "zoneUid": {
                    "type": "string"
                }
            }
        },
        "models.SystemHistory": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "changedAt": {
                    "type": "string"
                },
                "changedBy": {
                    "type": "string"
                },
                "detail": {
                    "$ref": "#/definitions/models.SystemHistoryDetail"
                },
                "historyType": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.SystemHistoryDetail": {
            "type": "object",
            "properties": {
                "direction": {
                    "type": "string"
                },
                "systemName": {
                    "type": "string"
                },
                "systemUid": {
                    "type": "string"
                }
            }
        },
        "models.SystemSimpleResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.SystemStatistics": {
            "type": "object",
            "properties": {
                "minimalSpareParstCount": {
                    "type": "number"
                },
                "sp_coverage": {
                    "type": "number"
                },
                "sparePartsCount": {
                    "type": "integer"
                },
                "sparePartsCoverageSum": {
                    "type": "number"
                },
                "subsystemsCount": {
                    "type": "integer"
                }
            }
        },
        "models.SystemTreeUid": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.SystemTreeUid"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.SystemsMovement": {
            "type": "object",
            "properties": {
                "systemsToMoveUids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "targetParentSystemUid": {
                    "type": "string"
                }
            }
        },
        "models.UserAuthInfo": {
            "type": "object",
            "properties": {
                "accessToken": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "facility": {
                    "type": "string"
                },
                "facilityCode": {
                    "type": "string"
                },
                "firstName": {
                    "type": "string"
                },
                "isEnabled": {
                    "type": "boolean"
                },
                "lastName": {
                    "type": "string"
                },
                "passwordHash": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uid": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.WosAPIResponse": {
            "type": "object",
            "properties": {
                "hits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WosHit"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/models.WosMetadata"
                }
            }
        },
        "models.WosAuthor": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                },
                "researcherId": {
                    "type": "string"
                },
                "wosStandard": {
                    "type": "string"
                }
            }
        },
        "models.WosCitation": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "db": {
                    "type": "string"
                }
            }
        },
        "models.WosEditor": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string"
                }
            }
        },
        "models.WosHit": {
            "type": "object",
            "properties": {
                "citations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WosCitation"
                    }
                },
                "identifiers": {
                    "$ref": "#/definitions/models.WosIdentifiers"
                },
                "keywords": {
                    "$ref": "#/definitions/models.WosKeywords"
                },
                "names": {
                    "$ref": "#/definitions/models.WosNames"
                },
                "source": {
                    "$ref": "#/definitions/models.WosSource"
                },
                "sourceTypes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "uid": {
                    "type": "string"
                }
            }
        },
        "models.WosIdentifiers": {
            "type": "object",
            "properties": {
                "doi": {
                    "type": "string"
                },
                "issn": {
                    "type": "string"
                }
            }
        },
        "models.WosKeywords": {
            "type": "object",
            "properties": {
                "authorKeywords": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.WosMetadata": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "models.WosNames": {
            "type": "object",
            "properties": {
                "authors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WosAuthor"
                    }
                },
                "bookEditors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.WosEditor"
                    }
                }
            }
        },
        "models.WosPages": {
            "type": "object",
            "properties": {
                "begin": {
                    "type": "string"
                },
                "count": {
                    "type": "integer"
                },
                "end": {
                    "type": "string"
                },
                "range": {
                    "type": "string"
                }
            }
        },
        "models.WosSource": {
            "type": "object",
            "properties": {
                "issue": {
                    "type": "string"
                },
                "pages": {
                    "$ref": "#/definitions/models.WosPages"
                },
                "publishMonth": {
                    "type": "string"
                },
                "publishYear": {
                    "type": "integer"
                },
                "sourceTitle": {
                    "type": "string"
                },
                "volume": {
                    "type": "string"
                }
            }
        },
        "panda_apigateway_services_catalogue-service_models.CatalogueItemDetail": {
            "type": "object",
            "properties": {
                "property": {
                    "$ref": "#/definitions/models.CatalogueCategoryProperty"
                },
                "propertyGroup": {
                    "type": "string"
                },
                "value": {}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token. \u003cbr\u003e How to obtain: https://eli-eric.atlassian.net/wiki/spaces/CS/pages/948797504/How+to+get+PANDA+API+Token \u003cbr\u003e Add word Bearer before the token here.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:50000",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "PANDA REST API - localhost",
	Description:      "This is the REST API to the PANDA database. \\n This is the only place to access data from the PANDA database.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
