basePath: /
host: localhost:50000
info:
  contact:
    email: jiri.svacha@eli-beams.eu
    name: Jiří Švácha
  description: This is the REST API to the PANDA database. \n This is the only place
    to access data from the PANDA database.
  title: PANDA REST API - localhost
  version: "1.0"
paths:
  /v1/order/{uid}:
    delete:
      description: Delete an order by order UID
      parameters:
      - description: Order UID
        in: path
        name: uid
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "401":
          description: Unauthorized
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Delete an order
      tags:
      - Orders
schemes:
- http
securityDefinitions:
  BearerAuth:
    description: 'JWT token. <br> How to obtain: https://eli-eric.atlassian.net/wiki/spaces/CS/pages/948797504/How+to+get+PANDA+API+Token
      <br> Add word Bearer before the token here.'
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
