openapi: 3.0.2
info:
  title: PANDA - API Gateway
  description: This is an API Gateway to the PANDA database. This is the only place to access data from the PANDA database.
  version: "1.0"
  contact:
    name: Jiří Švácha
    email: jiri.svacha@eli-beams.eu
  x-logo:
    url: eli-logo-small.png
servers:
  - url: "http://localhost:50000/v1"
    description: Local DEV server.
  - url: "http://localhost:5000/api/mock-server"
    description: Mock server. Part of the Next.js UI ui-main-app.
  - url: "https://api.panda.eli-beams.eu/v1"
    description: Production server.
tags:
  - name: Catalogue
    description: Everything about catalogue
  - name: Security
    description: Everything about authentication and authorization
components:
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: You can get the JWT if you successfully authenticate via /authenticate POST endpoint
paths:
  /authenticate:
    post:
      summary: Authentication of the user
      description: Authenticate user by username and password and return user info and JWT (json web token)
      operationId: AuthenticateByUsernameAndPassword
      tags:
        - Security
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: albert.einstein@eli-laser.eu
                password:
                  type: string
                  example: E=mc2
      responses:
        "200":
          description: Successfully authenticated. Returns user info with JWT.
          content:
            application/json:
              schema:
                $ref: "#/paths/~1authenticate/post/requestBody/content/application~1json/schema"
        "401":
          description: Unauthorized
        "500":
          description: General server error
  /refresh-token:
    post:
      summary: Refresh JWT
      description: "Refresh JWT (json web token) presented in the Authorization header. If the JWT have not expired yet, update and returns new JWT."
      operationId: RefreshToken
      security:
        - jwtAuth: []
      tags:
        - Security
      responses:
        "200":
          description: Successfully reauthenticated. Returns new JWT.
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOiIxMjM0NTY3ODk5In0.4UuocEvJTR3c1t2kB4f5lbRKfs5yKe7dW1Qtm_LITII
        "401":
          description: Unauthorized
        "500":
          description: General server error
  /authenticated-user:
    get:
      summary: Get user info by JWT presented in header
      description: Get user info by JWT (json we token) presented in Authorization header in the request
      operationId: GetUserByJWT
      security:
        - jwtAuth: []
      tags:
        - Security
      responses:
        "200":
          description: Returns user information from the JWT that was successfully chekced
          content:
            application/json:
              schema:
                type: object
                properties:
                  uid:
                    type: string
                    example: 71864520-9e86-427c-901c-0c220f951775
                  username:
                    type: string
                    example: albert.einstein@eli-laser.eu
                  fullName:
                    type: string
                    example: Albert Einstein
                  facility:
                    type: string
                    example: ELI ERIC
                  accessToken:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOiIxMjM0NTY3ODk5In0.4UuocEvJTR3c1t2kB4f5lbRKfs5yKe7dW1Qtm_LITII
                  roles:
                    type: array
                    items:
                      type: string
                    example:
                      - catalogue-view
                      - spare-parts-view
        "401":
          description: Unauthorized
        "500":
          description: General server error
  /catalogue/categories:
    get:
      summary: Get catalogue categories by parent path
      description: Get catalogue categories by parent path
      operationId: GetCatalogueCategoriesByParentPath
      security:
        - jwtAuth: []
      tags:
        - Catalogue
      parameters:
        - name: parentPath
          in: path
          description: Parent category path
          required: true
          schema:
            type: string
            example: vacuum-technology/vacuum-pumps
      responses:
        "200":
          description: Returns array of catalogue categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    uid:
                      type: string
                      example: 50b3844d-6cde-4980-bed5-388618cad292
                    name:
                      type: string
                      example: Dry Vacuum Pumps
                    code:
                      type: string
                      example: dry-vacuum-pumps
                    parent-path:
                      type: string
                      example: vacuum-technology/vacuum-pumps
        "401":
          description: Unauthorized
        "500":
          description: General server error
