name: Compose up REST API

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: czechia-server
    steps:
      - name: Show secret stats
        run: |
          echo "${{ secrets.API_JWT_SECRET }}" | echo "${{ secrets.NEO4J_PASSWORD }}" | echo "${{ secrets.API_INTEGRATION_B_OKBASE_API_KEY }}" | wc
  compose-up:
    runs-on: czechia-server
    needs: use-secret
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker compose up -d --build
        env:
          API_JWT_SECRET: "${{ secrets.API_JWT_SECRET }}"
          NEO4J_PASSWORD: "${{ secrets.NEO4J_PASSWORD }}"
          API_INTEGRATION_B_OKBASE_API_KEY: "${{ secrets.API_INTEGRATION_B_OKBASE_API_KEY }}"
