name: Compose up REST API

on:
  workflow_dispatch:

jobs:
  use-secret:
    runs-on: self-hosted
    steps:
      - name: Show secret stats
        run: |
          echo "${{ secrets.API_JWT_SECRET }}" | echo "${{ secrets.NEO4J_PASSWORD }}" | wc
  compose-up:
    runs-on: self-hosted
    needs: use-secret
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker-compose up -d --build
        env:
          API_JWT_SECRET: "${{ secrets.API_JWT_SECRET }}"
          NEO4J_PASSWORD: "${{ secrets.NEO4J_PASSWORD }}"
