name: Compose up TEST REST API on push

on:
  push:
    branches:
      - "main"

jobs:
  use-secret:
    runs-on: czechia-server
    steps:
      - name: Validate required secrets are set
        env:
          API_JWT_SECRET: "${{ secrets.API_JWT_SECRET }}"
          NEO4J_PASSWORD: "${{ secrets.NEO4J_PASSWORD }}"
          API_INTEGRATION_B_OKBASE_API_KEY: "${{ secrets.API_INTEGRATION_B_OKBASE_API_KEY }}"
        run: |
          test -n "$API_JWT_SECRET" || { echo "Error: API_JWT_SECRET is not set."; exit 1; }
          test -n "$NEO4J_PASSWORD" || { echo "Error: NEO4J_PASSWORD is not set."; exit 1; }
          test -n "$API_INTEGRATION_B_OKBASE_API_KEY" || { echo "Error: API_INTEGRATION_B_OKBASE_API_KEY is not set."; exit 1; }
  compose-up:
    runs-on: czechia-server
    needs: use-secret
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker compose -f docker-compose-test.yml up -d --build
        env:
          API_JWT_SECRET: "${{ secrets.API_JWT_SECRET }}"
          NEO4J_PASSWORD: "${{ secrets.NEO4J_PASSWORD }}"
          API_INTEGRATION_B_OKBASE_API_KEY: "${{ secrets.API_INTEGRATION_B_OKBASE_API_KEY }}"
